"use client";

import React from "react";
import { useQuery } from "convex/react";
import { api } from "@packages/backend/convex/_generated/api";
import { Label } from "@/components/ui/label";
import { Sparkles, Info } from "lucide-react";
import { useTranslations } from "@/hooks/use-translations";

export default function AISystem() {
  const persona = useQuery(api.queries.persona.getPersona);
  const { t } = useTranslations();

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Sparkles className="h-6 w-6 text-primary" />
          {t("profile.aiSystem.title")}
        </h1>
        <p className="text-sm text-muted-foreground mt-1">
          {t("profile.aiSystem.description")}
        </p>
      </div>

      <div className="space-y-4">
        {/* Info Box */}
        <div className="rounded-lg bg-primary/5 border border-primary/20 p-4 space-y-2">
          <div className="flex items-start gap-2">
            <Info className="h-5 w-5 text-primary shrink-0 mt-0.5" />
            <div className="space-y-1">
              <h3 className="text-sm font-semibold">
                {t("profile.aiSystem.autoGeneratedPrompt")}
              </h3>
              <p className="text-sm text-muted-foreground">
                {t("profile.aiSystem.autoGeneratedPromptDescription")}
              </p>
            </div>
          </div>
        </div>

        {/* AI Prompt Display */}
        <div className="space-y-3">
          <Label>{t("profile.aiSystem.currentPrompt")}</Label>
          <div className="rounded-lg border border-border bg-muted/30 p-4">
            {persona?.ai_prompt ? (
              <div className="space-y-2">
                <pre className="whitespace-pre-wrap font-mono text-sm leading-relaxed text-foreground">
                  {persona.ai_prompt}
                </pre>
              </div>
            ) : (
              <div className="text-center py-8 text-muted-foreground">
                <Sparkles className="h-8 w-8 mx-auto mb-2 opacity-50" />
                <p className="text-sm">{t("profile.aiSystem.noPrompt")}</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
